//
// Created by 夏申频 on 16/9/12.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_net_xyan_jnipp_JNISample */

#ifndef _Included_cn_net_xyan_jnipp_JNISample
#define _Included_cn_net_xyan_jnipp_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_net_xyan_jnipp_JNISample
 * Method:    read
 * Signature: (Ljava/io/InputStream;Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_cn_net_xyan_jnipp_JNISample_read
(JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
